### ISSUE TITLE
dist?

### ISSUE THREAD

**Issue by radiantmediaplayer** [streamroot/hlsjs-p2p-wrapper#116]
Can you provide the dist as well for your hls.js module?
There are step requirements to build this on Windows which most front-end dev do not meet.

**Comment by ruslandinov** [comment]
Hello @radiantmediaplayer , 
could you please tell us what do you mean by `dist`? Is it a result of `npm run build`, i.e. the actual build? 
And if it's so, could you please explain why exactly you need this? Your answer might help us in improving our build workflow and supporting different platforms(Windows, for example).

**Comment by radiantmediaplayer** [comment]
I need to retrieve the latest hlsjs-p2p-wrapper.js with Ajax. So yes the actual build. I cannot import your class in my project because not all our users are using streamroot and adding this will increase the size of our player. I work on Windows 10 and it took me an hour to debug all the build requirements so this is why I asked.
Also is hlsjs-p2p-wrapper.js fully ES5 compliant? or is it ES2015 only?

**Comment by radiantmediaplayer** [comment]
BTW you have a 404 on your README at https://streamroot.readme.io/docs/peeragent-class-reference

**Comment by tri170391** [comment]
Hello @radiantmediaplayer, I am the "Windows" guy in the team and I can help you in building this. Could you describe to me what problems you have.

About `ES2015/ES5` compliant, we use `babel` in our build which should trans-pile the code to `ES5`-compatible code.

**Comment by radiantmediaplayer** [comment]
I was able to build it but:
- we do not use WebPack (grunt)
- we do not use Ruby (PHP)
- we do not use node 6 (4)
- we do not use Cygwin (Git Bash) 
- wget is not available by default with Cygwin latest setup-x86_64.exe so you have to manually add it at install time

So in order to build your lib I had to install all of the above. I am just saying that having the latest build is a convenience for some users.

**Comment by tri170391** [comment]
You can fetch our latest stable build here: https://cdn.streamroot.io/hlsjs-p2p-wrapper/stable/hlsjs-p2p-wrapper.js

I will update our `README.md` about this soon. Thank you for your interest 👍

**Comment by jlouazel** [comment]
As #117 fixed this, I close this issue. @radiantmediaplayer feel free to reopen it in case of trouble.
